### ISSUE TITLE
Fix SampleLazy bug

### ISSUE THREAD

**Issue by the-real-blackh** [SodiumFRP/sodium-rust#23]
See https://github.com/SodiumFRP/sodium/issues/124

**Comment by clinuxrulz** [comment]
https://github.com/SodiumFRP/sodium-rust/commit/a6a5e13d2e91c26e4d8979a320394ad838bb2015
test that reveals the bug.

just working out how the view the 4 commits together as 1 set of changes to help spot the difference. Seems there is an extra queue now.
