### ISSUE TITLE
Check that switchS and split do not create node cycles

### ISSUE THREAD

**Issue by the-real-blackh** [SodiumFRP/sodium-rust#25]
This was fixed in the C# version. Make sure it's fixed in the Rust version.
https://github.com/SodiumFRP/sodium/commit/fb73c4305a58fcef81fa8a5406e97b1a61a3fe0b

**Comment by clinuxrulz** [comment]
No rank-wise dependencies between the produced stream via ```split``` and the original stream. So this should be all good, closing.
