### ISSUE TITLE
Streams of different types

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-rust#33]
Re-filed from [here](https://github.com/clinuxrulz/sodium-rust-push-pull/issues/3) since that repo is deprecated

Feel free to correct, but it seems we're really talking about two issues:

1. Documenting how one can create new Streams of any type - i.e. implementing a Trace Trait around a newtype wrapper? (not sure if that's really right, I need the docs ;P a common use case would be passing around a struct or enum)

2. Providing out of the box support for more built-in Copy types like f32 and f64 (not sure if other basics too?)

**Comment by clinuxrulz** [comment]
We really need trait specialization here. It is a part of rust nightly, but not in stable rust just yet. For now I guess we just implement it for all types that are a part of the std in the library.

Another problem though is 3rd party crates:

Crate 1: sodium lib
Crate 2: 3rd party lib
Crate 3: your app

In crate 3 you'd be forced to make wrapper types in order to use crate 2 types through cells / streams. There is a fair amount of boil plate. When nightly stabilizes we could have a better story here.

**Comment by clinuxrulz** [comment]
There is a fair few primitive types to impl for non-nightly users:
https://doc.rust-lang.org/1.9.0/book/primitive-types.html

Then tuples, fixed size arrays. It is very tedious.

**Comment by dakom** [comment]
At a glance it sounds like the technique you mentioned above is relying on a feature that will eventually make its way to stable?

Fwiw I'd imagine anyone using this lib would be cool with relying on nightly in the meantime. Just a guess though :)

**Comment by clinuxrulz** [comment]
Not sure. It might become ```partial impl``` when rust stabilise. The issue in the rust repo has been dragging on for over 2 years. At least the ```#[cfg(...``` still let's who ever is on nightly have it.

**Comment by clinuxrulz** [comment]
bit stange, I tried the ```#[cfg(feature = "nightly")]``` but the specialization did not seem to do anything when I went ```cargo +nightly build```. Oh well, all the primitive types are done, just need to do all the standard collection types now.

**Comment by dakom** [comment]
I haven't gotten to tinker with it yet - but I think one of the most important use cases will be holding Structs of (structs of) primitive types. For example, passing around something like a State object which doesn't have any methods but does have nested data

**Comment by clinuxrulz** [comment]
the switch_s_simultaneous test sort of has something like that.
https://github.com/SodiumFRP/sodium-rust/blob/master/src/tests/stream_test.rs#L671
Its a local struct, and you can/must provide local trait implementations. Implementing sodium traits on objects you own from your own crate/app is allowed in Rust.

**Comment by clinuxrulz** [comment]
@dakom how would you feel about a special type ```NoGc<A>``` (no garbage collector) for wrapping structs that someones does not want to do the trace/finalize trait impls for? (```NoGc<MyStruct>```)

**Comment by dakom** [comment]
I'm a Rust newbie - totally trust your judgement!

I think, whatever you decide - it would help make it more approachable to have documentation of some sort - perhaps even samples of typical uses cases (i.e. passing a primitive that has Copy around, passing a struct of primitives, passing a box, etc.)

Of course this is something which speaks to sodium more generally, but it's complicated by Rust's approach to memory management.

On one foot, a wrapper sounds easier to work with than requiring to implement traits.

**Comment by clinuxrulz** [comment]
Yeah. I've been a bit lazy on the documentation. I'll make sure to do a lot more of it in the code, then direct ppl to http://docs.rs . Even with ```NoGc<>``` there is still no escape from the ```Clone``` impl. You'd always need to define ```Clone``` or use ```Rc<A>``` which already defines ```Clone```

**Comment by clinuxrulz** [comment]
another slight issue. David_Blubaugh has inspired me to research more Rust targets. And I became aware that Rust can target bare metal targets such as the MSP430 (an ultra low power processor). With apparently runs at 33MHz and has a battery of.... 10 to 15 years 😮  . Which I found amazing. But I'm guessing that battery life is just for the processor itself, and such a device would not last as long if connected to some small LED monitor. Could be cool for someone wanting to make their own mini LED pacman or something.

That problem it causes is I'd have trait implementations for collection types from the standard library. And I'd need to compile without the standard library to target such platforms ```![no_std]```. Maybe a separate rust repo for bare metal?, not sure. I wont do anything about that now though.

Just standard library support for now :smile:

**Comment by clinuxrulz** [comment]
I've done all I can here for now. Some basic documentation is in the README.md. I went the ```NoGc<>``` path to dodge annoyances of having to define ```Trace``` / ```Finalize``` for every struct you defined in your program.
