### ISSUE TITLE
map w/ NoGc?

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-rust#36]
I'm probably just missing something basic, but I tried to send a simple Struct like the Readme- and then map that stream. Couldn't figure out how to get around the compiler error. Any tips?

Here's the closest I got, it fails on `s_mouse.map()`

```rust
#[derive(Clone)]
pub struct Point {
    x: f64,
    y: f64 
}

fn simpleTest(sodium_ctx: *const SodiumCtx) {
    let sodium_ctx = unsafe { &*sodium_ctx };
    
    let s_mouse: StreamSink<NoGc<Point>> = sodium_ctx.new_stream_sink();
    let s_world = s_mouse.map(|p:&NoGc<Point>| p);
}
```

**Comment by clinuxrulz** [comment]
the lambda type signature in map needs to be ```Fn(&NoGc<Point>)->NoGc<Point>``` instead of ```Fn(&NoGc<Point>)->&NoGc<Point>```. This is just in case there happens to be a fork in the frp graph (it needs to clone). 

Try:
```let s_world = s_mouse.map(|p:&NoGc<Point>| p.clone());```

**Comment by dakom** [comment]
It worked :) feel free to close this
