### ISSUE TITLE
Reformatting code (question)

### ISSUE THREAD

**Issue by RadicalZephyr** [SodiumFRP/sodium-rust#52]
Hi @clinuxrulz,

I wanted to ask if you would be all right with me reformatting the entire crate using the [standard Rust code formatting tool `rustfmt`](https://github.com/rust-lang/rustfmt#rustfmt-----).

While working inside Sodium I've really been noticing how much harder it is for me to quickly read and understand the code because it's not quite in that canonical format that I'm so used to. We could then add back in the piece of the former CI I took out which was supposed to be checking the code for correct formatting.

**Comment by clinuxrulz** [comment]
Yes you may to so.
