### ISSUE TITLE
Provide Drop-based API for Transactions

### ISSUE THREAD

**Issue by RadicalZephyr** [SodiumFRP/sodium-rust#53]
I think it should be possible to implement an API similar to what I'm seeing in your cxx-alt variant of sodium where a `Transaction` object can be created that keeps the transaction open as long as that struct is alive and closes the transaction when it is destructed. This would give the same sort of RAII-guard type benefits and allow the tests between the two variants to look MUCH more similar.

**Comment by clinuxrulz** [comment]
That is a good idea. I approve of it.
