### ISSUE TITLE
Provide a Drop-based API for Listener cancellation

### ISSUE THREAD

**Issue by RadicalZephyr** [SodiumFRP/sodium-rust#54]
I think it might also be useful to provide an opt-in Drop-based API for cancelling Listeners like the one described in #53 for Transactions.  This would let sodium users simply stash a handle to the `ListenerGuard` or whatever we call it in a struct that is related to that listener, or move it into the environment of a closure etc. so that the Listener gets automatically cleaned up when those items go out of scope.

For 3.0 it might even be nice to make that the default behavior and then if the user wants the Listener to live forever they can intentionally leak the Listener by calling a method on it.

**Comment by clinuxrulz** [comment]
Calling ```listen_weak``` will create a drop-based listener at the moment.

**Comment by RadicalZephyr** [comment]
Oh, awesome! I still haven't fully explored the API that currently exists
